### ISSUE TITLE
EC Sensor not working (Raspberry Pi 4)

### ISSUE THREAD

**Issue by Crevitus** [AnyLeaf/anyleaf-python#2]
Hi, I have wired up your EC sensor to my Raspberry Pi 4, with jumpers going from GND to GND, 3.3v to 3.3v and TX going to TX (GPIO 14 on the pi) and RX going to RX (GPIO 15 on the pi). Serial port is enabled.

I have placed the sensor in a test beaker of water and am running the following Python code:

```Python
import time
from anyleaf import EcSensor, OnBoard

delay = 1  # Time between measurements, in seconds
ec_sensor = EcSensor(K=1.0)

while True:
    print(f"conductivity: {ec_sensor.read(OnBoard())}")

    time.sleep(delay)
```

Expected: The EC reading
Actual: 'AttributeError: Problem getting data'

Any idea what is wrong?

**Comment by David-OConnor** [comment]
I will look into this and get back to you.

**Comment by David-OConnor** [comment]
What happens if you swap TX and RX? (Ie TX connected to RX and RX connected to TX)

**Comment by Crevitus** [comment]
Still the same error sadly. Error is in line 479 of \_\_init\_\_.py

**Comment by David-OConnor** [comment]
This is likely a fault in the module - I'll dig a little more, and send a replacement within the next few days if I can't figure it out.

**Comment by David-OConnor** [comment]
Sending out a new module tomorrow. Sorry about the trouble!

**Comment by Crevitus** [comment]
I've received the new module. All working now, thank you!

**Comment by David-OConnor** [comment]
Glad to hear it!
